//Coloque a musica para tocar quando iniciar o programa está sincronizada//
System.Console.ForegroundColor = ConsoleColor.Yellow;
System.Console.WriteLine("Bum Bum Tam Tam (MC Fioti)");
System.Console.WriteLine("");
System.Console.ResetColor();
Thread.Sleep(18660);

System.Console.WriteLine("É a flauta envolvente");
Thread.Sleep(1300);
System.Console.WriteLine("Que mexe com a mente");
Thread.Sleep(1500);
System.Console.WriteLine("De quem tá presente");
Thread.Sleep(1500);
System.Console.WriteLine("As novinha saliente");
Thread.Sleep(1700);
System.Console.WriteLine("Fica loucona");
Thread.Sleep(600);
System.Console.WriteLine("E se joga pra gente (eu falei assim pra ela)");
Thread.Sleep(5300);
System.Console.WriteLine("");

System.Console.ForegroundColor = ConsoleColor.Magenta;
System.Console.WriteLine("Vai com o bum bum tam tam");
Thread.Sleep(1800);
System.Console.WriteLine("Vem com o bum bum tam tam");
Thread.Sleep(1600);
System.Console.WriteLine("Vai mexe o bum bum tam tam");
Thread.Sleep(1800);
System.Console.WriteLine("Vem desce o bum bum tam tam");
Thread.Sleep(1800);
System.Console.WriteLine("Vai mexe o bum bum tam tam");
Thread.Sleep(1800);
System.Console.WriteLine("Vem desce o bum bum ");
Thread.Sleep(2300);
System.Console.WriteLine("Vai com o bum bum");
Thread.Sleep(1600);
System.Console.WriteLine("Vem com o bum bum (com o bum bum, com o bum bum)");
Thread.Sleep(5400);
System.Console.WriteLine("");
System.Console.ResetColor();

System.Console.WriteLine("Vai treme o bumbum");
Thread.Sleep(1160);
System.Console.WriteLine("Tam tam tam tam tam tam tam tam ");
Thread.Sleep(11600);
System.Console.WriteLine("Autenticamente falando");
Thread.Sleep(2200);
System.Console.WriteLine("E aí, pô");
Thread.Sleep(2800);
System.Console.WriteLine("Nós tá tipo como");
Thread.Sleep(17730);
System.Console.WriteLine("");

System.Console.WriteLine("É a flauta envolvente");
Thread.Sleep(1200);
System.Console.WriteLine("Que mexe com a mente");
Thread.Sleep(1500);
System.Console.WriteLine("De quem tá presente");
Thread.Sleep(1500);
System.Console.WriteLine("As novinha saliente");
Thread.Sleep(1700);
System.Console.WriteLine("Fica loucona");
Thread.Sleep(600);
System.Console.WriteLine("E se joga pra gente (eu falei assim pra ela)");
Thread.Sleep(5300);
System.Console.WriteLine("");

System.Console.ForegroundColor = ConsoleColor.Magenta;
System.Console.WriteLine("Vai com o bum bum tam tam");
Thread.Sleep(2000);
System.Console.WriteLine("Vem com o bum bum tam tam");
Thread.Sleep(1600);
System.Console.WriteLine("Vai mexe o bum bum tam tam");
Thread.Sleep(1800);
System.Console.WriteLine("Vem desce o bum bum tam tam");
Thread.Sleep(1800);
System.Console.WriteLine("Vai mexe o bum bum tam tam");
Thread.Sleep(1800);
System.Console.WriteLine("Vem desce o bum bum ");
Thread.Sleep(2000);
System.Console.WriteLine("Vai com o bum bum");
Thread.Sleep(1800);
System.Console.WriteLine("Vem com o bum bum (com o bum bum, com o bum bum)");
Thread.Sleep(5300);
System.Console.WriteLine("");
System.Console.ResetColor();

System.Console.WriteLine("Vai treme o bumbum");
Thread.Sleep(1160);
System.Console.WriteLine("Tam tam tam tam tam tam tam tam ");
Thread.Sleep(11600);
System.Console.WriteLine("Autenticamente falando");
Thread.Sleep(2300);
System.Console.WriteLine("E aí, pô");
Thread.Sleep(3000);
System.Console.WriteLine("Nós tá tipo como");
Thread.Sleep(24100);